import crypto from 'crypto';
function clean(v){return String(v||'').trim()}
export function paymentMode(){return clean(process.env.PAYMENT_MODE).toLowerCase()==='xendit'?'xendit':'manual'}
export function apiKey(){return clean(process.env.XENDIT_SECRET_KEY)}
export function webhookToken(){return clean(process.env.XENDIT_WEBHOOK_TOKEN)}
export function credentialsReady(){return apiKey().length>10}
export function webhookReady(){return webhookToken().length>6}
export function xenditEnabled(){return paymentMode()==='xendit'&&credentialsReady()&&webhookReady()&&/^https:\/\//i.test(clean(process.env.SITE_URL))}
export function isProduction(){return !/^xnd_development_/i.test(apiKey())}
function auth(){return 'Basic '+Buffer.from(apiKey()+':').toString('base64')}
function err(msg,status=502,code='XENDIT_ERROR'){const e=new Error(msg);e.safe=true;e.status=status;e.code=code;return e}
async function call(path,opt={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch('https://api.xendit.co'+path,{...opt,signal:c.signal,headers:{Authorization:auth(),Accept:'application/json','Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw err(String(d.message||d.error_code||`Xendit HTTP ${r.status}`).slice(0,500),502,d.error_code||'API');return d}catch(e){if(e.name==='AbortError')throw err('Koneksi Xendit timeout. Silakan coba lagi.',504,'TIMEOUT');throw e}finally{clearTimeout(t)}}
export async function createPayment(order){if(!xenditEnabled())throw err('Xendit belum siap. Periksa XENDIT_SECRET_KEY, XENDIT_WEBHOOK_TOKEN, SITE_URL.',500,'CONFIG');const site=clean(process.env.SITE_URL).replace(/\/$/,'');const ref=String(order.id).slice(0,64);return call('/sessions',{method:'POST',body:JSON.stringify({reference_id:ref,session_type:'PAY',mode:'PAYMENT_LINK',amount:Number(order.total),currency:'IDR',country:'ID',capture_method:'AUTOMATIC',locale:'id',description:`Uply Digital - ${String(order.product_name||'Pesanan').slice(0,120)}`,success_return_url:`${site}/?payment_return=${encodeURIComponent(ref)}#pesanan/${encodeURIComponent(ref)}`,cancel_return_url:`${site}/#pesanan/${encodeURIComponent(ref)}`,customer:{reference_id:String(order.user_id||ref).slice(0,64),type:'INDIVIDUAL',email:String(order.email||'').slice(0,190),mobile_number:String(order.phone||'').startsWith('+')?String(order.phone):'+'+String(order.phone||''),individual_detail:{given_names:String(order.name||'Pelanggan').replace(/[^a-zA-Z0-9 ]/g,' ').slice(0,50)||'Pelanggan'}},items:[{reference_id:String(order.product_id||'product').slice(0,255),type:'DIGITAL_PRODUCT',name:String(order.product_name||'Produk Digital').slice(0,255),net_unit_amount:Number(order.price),quantity:Number(order.quantity)||1}]})})}
export async function getPaymentStatus(sessionId){if(!sessionId)throw err('Payment Session ID belum tersedia.',400);return call('/sessions/'+encodeURIComponent(sessionId))}
export function classifyPayment(p){const s=String(p?.status||'').toUpperCase();if(s==='COMPLETED'||s==='SUCCEEDED')return 'success';if(['EXPIRED','CANCELED','FAILED'].includes(s))return 'failed';return 'pending'}
export function verifyWebhookToken(v){const a=Buffer.from(clean(v)),b=Buffer.from(webhookToken());return a.length===b.length&&a.length>0&&crypto.timingSafeEqual(a,b)}
